#!/usr/bin/python3

import tkinter as tk

root = tk.Tk()
root.title("Othello")

btn_opts = {"width":4, "height":2, "font":("Arial", 36)}

button00 = tk.Button(root, **btn_opts, command=lambda: button_click("00"))
button01 = tk.Button(root, **btn_opts, command=lambda: button_click("01"))
button02 = tk.Button(root, **btn_opts, command=lambda: button_click("02"))
button03 = tk.Button(root, **btn_opts, command=lambda: button_click("03"))
button04 = tk.Button(root, **btn_opts, command=lambda: button_click("04"))
button05 = tk.Button(root, **btn_opts, command=lambda: button_click("05"))
button06 = tk.Button(root, **btn_opts, command=lambda: button_click("06"))
button07 = tk.Button(root, **btn_opts, command=lambda: button_click("07"))
button10 = tk.Button(root, **btn_opts, command=lambda: button_click("10"))
button11 = tk.Button(root, **btn_opts, command=lambda: button_click("11"))
button12 = tk.Button(root, **btn_opts, command=lambda: button_click("12"))
button13 = tk.Button(root, **btn_opts, command=lambda: button_click("13"))
button14 = tk.Button(root, **btn_opts, command=lambda: button_click("14"))
button15 = tk.Button(root, **btn_opts, command=lambda: button_click("15"))
button16 = tk.Button(root, **btn_opts, command=lambda: button_click("16"))
button17 = tk.Button(root, **btn_opts, command=lambda: button_click("17"))
button20 = tk.Button(root, **btn_opts, command=lambda: button_click("20"))
button21 = tk.Button(root, **btn_opts, command=lambda: button_click("21"))
button22 = tk.Button(root, **btn_opts, command=lambda: button_click("22"))
button23 = tk.Button(root, **btn_opts, command=lambda: button_click("23"))
button24 = tk.Button(root, **btn_opts, command=lambda: button_click("24"))
button25 = tk.Button(root, **btn_opts, command=lambda: button_click("25"))
button26 = tk.Button(root, **btn_opts, command=lambda: button_click("26"))
button27 = tk.Button(root, **btn_opts, command=lambda: button_click("27"))
button30 = tk.Button(root, **btn_opts, command=lambda: button_click("30"))
button31 = tk.Button(root, **btn_opts, command=lambda: button_click("31"))
button32 = tk.Button(root, **btn_opts, command=lambda: button_click("32"))
button33 = tk.Button(root, **btn_opts, command=lambda: button_click("33"))
button34 = tk.Button(root, **btn_opts, command=lambda: button_click("34"))
button35 = tk.Button(root, **btn_opts, command=lambda: button_click("35"))
button36 = tk.Button(root, **btn_opts, command=lambda: button_click("36"))
button37 = tk.Button(root, **btn_opts, command=lambda: button_click("37"))
button40 = tk.Button(root, **btn_opts, command=lambda: button_click("40"))
button41 = tk.Button(root, **btn_opts, command=lambda: button_click("41"))
button42 = tk.Button(root, **btn_opts, command=lambda: button_click("42"))
button43 = tk.Button(root, **btn_opts, command=lambda: button_click("43"))
button44 = tk.Button(root, **btn_opts, command=lambda: button_click("44"))
button45 = tk.Button(root, **btn_opts, command=lambda: button_click("45"))
button46 = tk.Button(root, **btn_opts, command=lambda: button_click("46"))
button47 = tk.Button(root, **btn_opts, command=lambda: button_click("47"))
button50 = tk.Button(root, **btn_opts, command=lambda: button_click("50"))
button51 = tk.Button(root, **btn_opts, command=lambda: button_click("51"))
button52 = tk.Button(root, **btn_opts, command=lambda: button_click("52"))
button53 = tk.Button(root, **btn_opts, command=lambda: button_click("53"))
button54 = tk.Button(root, **btn_opts, command=lambda: button_click("54"))
button55 = tk.Button(root, **btn_opts, command=lambda: button_click("55"))
button56 = tk.Button(root, **btn_opts, command=lambda: button_click("56"))
button57 = tk.Button(root, **btn_opts, command=lambda: button_click("57"))
button60 = tk.Button(root, **btn_opts, command=lambda: button_click("60"))
button61 = tk.Button(root, **btn_opts, command=lambda: button_click("61"))
button62 = tk.Button(root, **btn_opts, command=lambda: button_click("62"))
button63 = tk.Button(root, **btn_opts, command=lambda: button_click("63"))
button64 = tk.Button(root, **btn_opts, command=lambda: button_click("64"))
button65 = tk.Button(root, **btn_opts, command=lambda: button_click("65"))
button66 = tk.Button(root, **btn_opts, command=lambda: button_click("66"))
button67 = tk.Button(root, **btn_opts, command=lambda: button_click("67"))
button70 = tk.Button(root, **btn_opts, command=lambda: button_click("70"))
button71 = tk.Button(root, **btn_opts, command=lambda: button_click("71"))
button72 = tk.Button(root, **btn_opts, command=lambda: button_click("72"))
button73 = tk.Button(root, **btn_opts, command=lambda: button_click("73"))
button74 = tk.Button(root, **btn_opts, command=lambda: button_click("74"))
button75 = tk.Button(root, **btn_opts, command=lambda: button_click("75"))
button76 = tk.Button(root, **btn_opts, command=lambda: button_click("76"))
button77 = tk.Button(root, **btn_opts, command=lambda: button_click("77"))

button00.grid(row=0, column=0)
button01.grid(row=0, column=1)
button02.grid(row=0, column=2)
button03.grid(row=0, column=3)
button04.grid(row=0, column=4)
button05.grid(row=0, column=5)
button06.grid(row=0, column=6)
button07.grid(row=0, column=7)
button10.grid(row=1, column=0)
button11.grid(row=1, column=1)
button12.grid(row=1, column=2)
button13.grid(row=1, column=3)
button14.grid(row=1, column=4)
button15.grid(row=1, column=5)
button16.grid(row=1, column=6)
button17.grid(row=1, column=7)
button20.grid(row=2, column=0)
button21.grid(row=2, column=1)
button22.grid(row=2, column=2)
button23.grid(row=2, column=3)
button24.grid(row=2, column=4)
button25.grid(row=2, column=5)
button26.grid(row=2, column=6)
button27.grid(row=2, column=7)
button30.grid(row=3, column=0)
button31.grid(row=3, column=1)
button32.grid(row=3, column=2)
button33.grid(row=3, column=3)
button34.grid(row=3, column=4)
button35.grid(row=3, column=5)
button36.grid(row=3, column=6)
button37.grid(row=3, column=7)
button40.grid(row=4, column=0)
button41.grid(row=4, column=1)
button42.grid(row=4, column=2)
button43.grid(row=4, column=3)
button44.grid(row=4, column=4)
button45.grid(row=4, column=5)
button46.grid(row=4, column=6)
button47.grid(row=4, column=7)
button50.grid(row=5, column=0)
button51.grid(row=5, column=1)
button52.grid(row=5, column=2)
button53.grid(row=5, column=3)
button54.grid(row=5, column=4)
button55.grid(row=5, column=5)
button56.grid(row=5, column=6)
button57.grid(row=5, column=7)
button60.grid(row=6, column=0)
button61.grid(row=6, column=1)
button62.grid(row=6, column=2)
button63.grid(row=6, column=3)
button64.grid(row=6, column=4)
button65.grid(row=6, column=5)
button66.grid(row=6, column=6)
button67.grid(row=6, column=7)
button70.grid(row=7, column=0)
button71.grid(row=7, column=1)
button72.grid(row=7, column=2)
button73.grid(row=7, column=3)
button74.grid(row=7, column=4)
button75.grid(row=7, column=5)
button76.grid(row=7, column=6)
button77.grid(row=7, column=7)

root.mainloop()

